### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by 1281152329** [denpamusic/php-bitcoinrpc#10]
Problem 1
    - The requested package denpa/php-bitcoinrpc No version set (parsed as 1.0.0) is satisfiable by denpa/php-bitcoinrpc[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
please could tell me how to solve it.very thanks

**Comment by denpamusic** [comment]
Try running `composer clear-cache && composer update`.

If this doesn't fix the problem, please provide your `composer.json` file and output of following command `composer --version`.

**Comment by 1281152329** [comment]
After I run the command ,It still shows the same error。
What should I do with it?

**Comment by 1281152329** [comment]
when i try running composer update,it shows the error.like running composer resquire.
"Installation failed, reverting ./composer.json to its original content."

**Comment by denpamusic** [comment]
OK. Can you please run `composer --version` and post it's output here. I'll try to replicate your error.

**Comment by 1281152329** [comment]
Composer version 1.6.5
我又遇到了一个麻烦，天呐
上午的时候我重新从git上下载了一份代码，然后重新composer，结果
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: denpa/php-bitcoinrpc[v2.0.0, dev-master].
    - Can only install one of: denpa/php-bitcoinrpc[v2.0.1, dev-master].
    - Can only install one of: denpa/php-bitcoinrpc[v2.0.2, dev-master].
    - Can only install one of: denpa/php-bitcoinrpc[v2.0.3, dev-master].
    - Installation request for denpa/php-bitcoinrpc dev-master -> satisfiable by denpa/php-bitcoinrpc[dev-master].
    - Installation request for denpa/php-bitcoinrpc ^2.0 -> satisfiable by denpa/php-bitcoinrpc[v2.0.0, v2.0.1, v2.0.2, v2.0.3].


Installation failed, reverting ./composer.json to its original content.
虽然我根本没有装成功但是我尝试去删除这个依赖
但是它提示我
Package "denpa/php-bitcoinrpc" listed for update is not installed. Ignoring.
然后重新装勒composer但是还是没有用
我被困在这儿了

**Comment by 1281152329** [comment]
I'm sorry, I'll say it again in English.
I have a trouble again, oh my god.
In the morning, I downloaded the code from GIT and restarted composer.the result is:
Your requirements could not be resolved to an installable set of packages.Problem 1
- Can only install one of: denpa/php-bitcoinrpc[v2.0.0, dev-master].
- Can only install one of: denpa/php-bitcoinrpc[v2.0.1, dev-master].
- Can only install one of: denpa/php-bitcoinrpc[v2.0.2, dev-master].
- Can only install one of: denpa/php-bitcoinrpc[v2.0.3, dev-master].
- Installation request for denpa/php-bitcoinrpc dev-master -> satisfiable by denpa/php-bitcoinrpc[dev-master].
- Installation request for denpa/php-bitcoinrpc ^2.0 -> satisfiable by denpa/php-bitcoinrpc[v2.0.0, v2.0.1, v2.0.2, v2.0.3].

Installation failed, reverting ./composer.json to its original content.

Although I didn't   succeess, I tried to delete this dependency.
But it hints me:
Package "denpa/php-bitcoinrpc" listed for update is not installed. Ignoring.
So,i have to uninstall composer  and Reinstall it  ，but  there is no use
what should i do?
I'm very confused

**Comment by denpamusic** [comment]
To delete dependency, open `composer.json` find 'require' section, that looks like this
```
"require": {
    ...
    "denpa/php-bitcoinrpc": "...",
    ...
},
```
delete string that starts with "denpa/php-bitcoinrpc".
Finally delete `composer.lock` file and run `composer update`.

**Comment by denpamusic** [comment]
If possible it's will also be great if you can post your `composer.json` file here(a least "require" and "require-dev" section of it). If it contains any private information you can of course delete it.

**Comment by 1281152329** [comment]
my composer.json file  is the same as yours

**Comment by 1281152329** [comment]
first,i delete string that starts with "denpa/php-bitcoinrpc". and delete composer.lock file 
second,i composer update,It's normal.
third，i coomposer require  denpa/php-bitcoinrpc，
the question continued；
composer.json file：

{
    "name": "denpa/php-bitcoinrpc",
    "type": "library",
    "description": "Bitcoin JSON-RPC client based on GuzzleHttp",
    "keywords": ["bitcoin","api","jsonrpc","guzzle"],
    "homepage": "https://github.com/denpamusic/php-bitcoinrpc",
    "license": "MIT",
    "authors": [
        {
            "name": "Denis Paavilainen",
            "email": "denpa@netfleet.space",
            "role": "Developer"
        }
    ],
    "require": {
       
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7 || ^6.4 || ^7.0"
    },
    "autoload": {
        "psr-4" : {
            "Denpa\\Bitcoin\\": "src"
        },
        "classmap" : [
            "tests"
        ]
    }
}

**Comment by 1281152329** [comment]
I think this problem misleads me.

I'm stuck in it

**Comment by denpamusic** [comment]
I want to help you, but I think you're using composer wrong as you're not supposed download this package from github and then run composer on it. What you supposed to do, is to create your own project and then install php-bitcoinrpc via composer.

As this is probably your first time dealing with composer package I'll try to explain in detail. For this example I'm going to assume you work in linux environment.

1. First create directory in which your project will reside, lets call it `myproject`:
`mkdir myproject`
2. Then enter your newly created directory:
`cd myproject`
3. Run `composer require denpa/php-bitcoinrpc "^2.0"`. You should get message "./composer.json has been created" and package will install with it's dependencies:
4. Then you can create first file(let's call it index.php) of your project and include composer-generated autoloader in it:
`echo "<?php" > index.php && echo "require 'vendor/autoload.php';" >> index.php`
5. Now you can write your own code in index.php as described in [examples in README](https://github.com/denpamusic/php-bitcoinrpc/blob/master/README.md#usage) file.

**Comment by 1281152329** [comment]
It's very kind of you.I use it for the first time.I will do as you say.hope I am allowed to consult you in the future if I have any problem.

**Comment by denpamusic** [comment]
Of course you can consult me anytime. I'll try to respond as fast as I can.
Although you'd probably want to use gitter for general support: https://gitter.im/php-bitcoinrpc/Lobby since it's not a issue with php-bitcoinrpc package itself.

**Comment by 1281152329** [comment]
Thank you very much. Everything went well.
Let's get in touch later.
