### ISSUE TITLE
Different requirements in README.md and in composer.json

### ISSUE THREAD

**Issue by vladyslavstartsev** [denpamusic/php-bitcoinrpc#11]
in composer.json you have
https://github.com/denpamusic/php-bitcoinrpc/blob/2e1cd8a33153c644f00d2d24fad896abfc394260/composer.json#L16
in README.md you have
https://github.com/denpamusic/php-bitcoinrpc/blob/2e1cd8a33153c644f00d2d24fad896abfc394260/README.md#L16-L17

If 5.6 is not supported, then it should be dropped. Am I correct?

**Comment by denpamusic** [comment]
You're not wrong, as script developed with php 7 in mind. Once php 5.6 hit official End-of-Life, which will be on 2018-12-31 as stated [here](http://php.net/supported-versions.php) I'll also fully drop support for it in composer and CI (probably by creating new branch - v2.1.x re-implementing some things with nicer php7-only syntax)

For now my stance is that, if you want to use php 5.6, you still can but I won't provide support(as in technical support) in case something doesn't work. With that said travis CI [configuration for this project](https://github.com/denpamusic/php-bitcoinrpc/blob/master/.travis.yml#L4) still includes php 5.6, so it should be pretty safe to use, I just want to incentivize people to switch to php 7.

**Comment by vladyslavstartsev** [comment]
Sure! Got it! 🙂

**Comment by vladyslavstartsev** [comment]
Sure! Got it! 🙂
