### ISSUE TITLE
Linux 500 Internal Server Error when attempting to make request

### ISSUE THREAD

**Issue by Garlicvideos** [denpamusic/php-bitcoinrpc#13]
I have bitcoind open, tested and works with bitcoin-cli. Currently, when I do “bitcoind->getwalletinfo()->result();”, or rather any request at all, it will return an internal server error (500). I just moved the files which previously works on a windows computer to a linux VPS, installed a fresh version of thisibrary using linux Composer and made sure all the files were in the correct directories. Pls help ;-;

**Comment by denpamusic** [comment]
Hi, I don't know how it worked before, but the syntax you provided is incorrect.
Try calling it like this:
```
$bitcoind->getwalletinfo()->get();
```

**Comment by Garlicvideos** [comment]
Thanks for the reply, the error log is as follows:

`[Sat Sep 08 06:22:17.838825 2018] [:error] [pid 18382] [client 174.85.255.102:44458] PHP Fatal error:  Uncaught Denpa\Bitcoin\Exceptions\BitcoindException: getwalletinfo
Returns an object containing various wallet state info.

Result:
{
  "walletname": xxxxx,             (string) the wallet name
  "walletversion": xxxxx,          (numeric) the wallet version
  "balance": xxxxxxx,              (numeric) the total confirmed balance of the wallet in TUX
  "unconfirmed_balance": xxx,      (numeric) the total unconfirmed balance of the wallet in TUX
  "immature_balance": xxxxxx,      (numeric) the total immature balance of the wallet in TUX
  "txcount": xxxxxxx,              (numeric) the total number of transactions in the wallet
  "keypoololdest": xxxxxx,         (numeric) the timestamp (seconds since Unix epoch) of the oldest pre-generated key in the key pool
  "keypoolsize": xxxx,             (numeric) how many new keys are pre-generated (only counts external keys)
  "keypoolsize_hd_internal": xxxx, (numeric) how many new keys are pre-generated for internal use (used for change outputs, only appears if the wall in /home/garlicvideos/server-files/html/tuxcoind/vendor/denpa/php-bitcoinrpc/src/Client.php on line 151, referer: <ipaddress>/index.php`

**Comment by denpamusic** [comment]
Glad it worked for you in the end!
Though I really wonder what went wrong in the first place.
From your log it seems that you're using tuxcoin daemon.
Could you please specify which version.
I'll install it to the test server, just in case it happens again.

**Comment by Garlicvideos** [comment]
I’m currently using their latest version, 0.17.1. I hope you find out what went wrong.

**Comment by denpamusic** [comment]
Maybe related to https://github.com/denpamusic/laravel-bitcoinrpc/issues/8.
Should be completely fixed now.
