### ISSUE TITLE
How can I send BTC to another Address

### ISSUE THREAD

**Issue by DevBiiTz** [denpamusic/php-bitcoinrpc#6]
_Sorry for my ignorance but how can I send bitcoins to another address?
I'm trying_

`$send = $BTC->request('sendtoaddress', '*************************************************** 0.06');`

_Any example or not is possible?_

**Thanks ;D and good job.**

**Comment by denpamusic** [comment]
Hi!
Thank you for your feedback!
Arguments for Bitcoin Core must be passed as array if you're using request() method.
For example:
```
$result = $BTC->request('sendtoaddress', ['mmXgiR6KAhZCyQ8ndr2BCfEq1wNG2UnyG6', 0.06]);
```
Note the square brackets on arguments.
You can also use magic method to perform the same request:
```
$result = $BTC->sendToAddress('mmXgiR6KAhZCyQ8ndr2BCfEq1wNG2UnyG6', 0.06);
```
I'll try to improve README with more examples later.

**Comment by DevBiiTz** [comment]
@denpamusic Thanks for help me ;D, You can add for Donate BTC Address ? I would like to donate you BTC

**Comment by denpamusic** [comment]
Glad I could help you :)
Don't hesitate to ask if you have any more problems or questions.

If you like to donate, you can donate BTC to **13gkVWc3sdzpmCLkGkXXfPBwnh6ZXct947**
I also added this donation address as well as sendToAddress example to README.

**Comment by DevBiiTz** [comment]
@denpamusic BTC sended in aprox 1hour thanks for your work men
